import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface PathwayPDFData {
  career: string;
  pathway: string;
  track: string;
  fitPercentage: number;
  confidence: string;
  combinations: Array<{
    name: string;
    subjects: string[];
    rank?: number;
    score?: number;
  }>;
  schools?: Array<{
    name: string;
    location: string;
    type: string;
  }>;
  date: string;
}

export function generatePathwayPDF(data: PathwayPDFData): string {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header branding
  doc.setFontSize(20);
  doc.setTextColor(0, 102, 204);
  doc.text('ElimuX', 14, 20);
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text('Career Pathway Report', 14, 27);
  doc.setFontSize(9);
  doc.text(`Generated: ${data.date} | www.elimux.ke`, 14, 33);

  // Horizontal rule
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 37, pageWidth - 14, 37);

  // Career summary
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(data.career, 14, 48);

  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(`Pathway: ${data.pathway}`, 14, 55);
  doc.text(`Track: ${data.track}`, 14, 61);
  doc.text(`Match Score: ${data.fitPercentage}% (${data.confidence} confidence)`, 14, 67);

  // Match score bar
  const barY = 73;
  doc.setFillColor(230, 230, 230);
  doc.roundedRect(14, barY, 80, 6, 2, 2, 'F');
  const barColor = data.fitPercentage >= 70 ? [0, 150, 100] : data.fitPercentage >= 40 ? [255, 180, 0] : [220, 60, 60];
  doc.setFillColor(barColor[0], barColor[1], barColor[2]);
  doc.roundedRect(14, barY, 80 * (data.fitPercentage / 100), 6, 2, 2, 'F');

  // Subject Combinations table
  let startY = 88;
  if (data.combinations && data.combinations.length > 0) {
    doc.setFontSize(13);
    doc.setTextColor(0, 0, 0);
    doc.text('Recommended Subject Combinations', 14, startY);

    autoTable(doc, {
      startY: startY + 5,
      head: [['Rank', 'Combination', 'Subjects', 'Suitability']],
      body: data.combinations.map((c, idx) => [
        idx + 1,
        c.name,
        c.subjects.join(', '),
        c.score ? `${c.score}%` : '—',
      ]),
      theme: 'striped',
      headStyles: { fillColor: [0, 102, 204], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 249, 250] },
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: {
        0: { cellWidth: 15, halign: 'center' },
        1: { cellWidth: 55 },
        2: { cellWidth: 'auto' },
        3: { cellWidth: 25, halign: 'center' },
      },
      margin: { left: 14, right: 14 },
    });

    startY = (doc as any).lastAutoTable.finalY + 10;
  }

  // Schools table
  if (data.schools && data.schools.length > 0) {
    doc.setFontSize(13);
    doc.text('Recommended Schools', 14, startY);

    autoTable(doc, {
      startY: startY + 5,
      head: [['School', 'Location', 'Type']],
      body: data.schools.map((s) => [s.name, s.location, s.type]),
      theme: 'striped',
      headStyles: { fillColor: [0, 150, 100], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 249, 250] },
      styles: { fontSize: 9, cellPadding: 3 },
      margin: { left: 14, right: 14 },
    });
  }

  // Footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      'This report is generated by ElimuX based on KJSA analysis. Consult your school career guidance counselor for final subject selections.',
      14,
      doc.internal.pageSize.getHeight() - 10
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 30, doc.internal.pageSize.getHeight() - 10);
  }

  // jsPDF v4's 'bloburl' output returns a URL object, not a string (a
  // typing change from older versions) - convert so callers assigning
  // straight to an anchor's .href (a string setter) don't need to know.
  return doc.output('bloburl').toString();
}
