-- Cycle 051: School Discovery seed data
-- senior_schools: all 204 rows are REAL C1 (national/most-selective tier)
-- public secondary schools, extracted and parsed directly from the official
-- "C1 - PUBLIC SENIOR SCHOOLS IN KENYA" KEMIS PDF (region, county, sub-county,
-- UIC code, KNEC code, name, gender, accommodation all sourced from that
-- document — not hand-written or approximated). C2-C4 (county/sub-county/day
-- schools, ~205k more rows combined across the other 3 PDFs) are deferred to
-- a later ingestion pass; this Phase 1 seed intentionally covers C1 only.

INSERT INTO senior_schools
  (id, name, region, county, sub_county, cluster_type, gender, accommodation_type, school_type, knec_code, uic_code)
VALUES
(gen_random_uuid(), 'Kabarnet High School', 'Rift Valley', 'Baringo', 'Baringo Central', 'C1', 'Boys', 'Boarding', 'Regular', '33517201', 'CD36'),
(gen_random_uuid(), 'Kapropita Girls High School', 'Rift Valley', 'Baringo', 'Baringo Central', 'C1', 'Girls', 'Boarding', 'Regular', '33517202', '8WY3'),
(gen_random_uuid(), 'Ossen Secondary School', 'Rift Valley', 'Baringo', 'Baringo North', 'C1', 'Girls', 'Boarding', 'Regular', '33500019', '2V5E'),
(gen_random_uuid(), 'Baringo Boys High School', 'Rift Valley', 'Baringo', 'Koibatek', 'C1', 'Boys', 'Boarding', 'Regular', '33500018', 'HLWY'),
(gen_random_uuid(), 'Tenwek High School', 'Rift Valley', 'Bomet', 'Bomet Central', 'C1', 'Boys', 'Boarding', 'Regular', '25500023', '57ZH'),
(gen_random_uuid(), 'Moi Siongiroi Girls'' Secondary School', 'Rift Valley', 'Bomet', 'Chepalungu', 'C1', 'Girls', 'Boarding', 'Regular', '25551207', '5NH8'),
(gen_random_uuid(), 'Kaplong Boys High School', 'Rift Valley', 'Bomet', 'Sotik', 'C1', 'Boys', 'Boarding', 'Regular', '25533103', 'Q2BT'),
(gen_random_uuid(), 'Kaplong Girls Secondary School', 'Rift Valley', 'Bomet', 'Sotik', 'C1', 'Girls', 'Boarding', 'Regular', '25500019', '2YKS'),
(gen_random_uuid(), 'Cardinal Otunga Girls High School', 'Western', 'Bungoma', 'Bungoma South', 'C1', 'Girls', 'Boarding', 'Regular', '36602103', 'YAU5'),
(gen_random_uuid(), 'Kibabii High School', 'Western', 'Bungoma', 'Bungoma South', 'C1', 'Boys', 'Boarding', 'Regular', '36602102', 'N7CB'),
(gen_random_uuid(), 'Friends Kamusinga', 'Western', 'Bungoma', 'Kimilili', 'C1', 'Boys', 'Boarding', 'Regular', '36600004', 'VMZ9'),
(gen_random_uuid(), 'Moi Girls High School, Kamusinga', 'Western', 'Bungoma', 'Kimilili', 'C1', 'Girls', 'Boarding', 'Regular', '36621108', 'VJ73'),
(gen_random_uuid(), 'Lugulu Girls', 'Western', 'Bungoma', 'Webuye West', 'C1', 'Girls', 'Boarding', 'Regular', '36600002', 'GV53'),
(gen_random_uuid(), 'St. Stephens Lwanya Girls Secondary', 'Western', 'Busia', 'Busia', 'C1', 'Girls', 'Boarding', 'Regular', '35601202', 'REWP'),
(gen_random_uuid(), 'Butula Boys High School', 'Western', 'Busia', 'Butula', 'C1', 'Boys', 'Boarding', 'Regular', '35600007', '6UPN'),
(gen_random_uuid(), 'Nambale Secondary School', 'Western', 'Busia', 'Nambale', 'C1', 'Boys', 'Boarding', 'Regular', '35629101', 'ZEFL'),
(gen_random_uuid(), 'S.A. Kolanya Girls Secondary School', 'Western', 'Busia', 'Teso North', 'C1', 'Girls', 'Boarding', 'Regular', '35600008', 'VHTB'),
(gen_random_uuid(), 'St Patrick Iten', 'Rift Valley', 'Elgeyo Marakwet', 'Keiyo North', 'C1', 'Boys', 'Boarding', 'Regular', '34500010', 'QYWY'),
(gen_random_uuid(), 'Metkei Girls Secondary', 'Rift Valley', 'Elgeyo Marakwet', 'Keiyo South', 'C1', 'Girls', 'Boarding', 'Regular', '34559502', 'MQUJ'),
(gen_random_uuid(), 'Moi Kapsowar Girls', 'Rift Valley', 'Elgeyo Marakwet', 'Marakwet West', 'C1', 'Girls', 'Boarding', 'Regular', '34500017', '2RPN'),
(gen_random_uuid(), 'Kyeni Girls'' High School', 'Eastern', 'Embu', 'Embu East', 'C1', 'Girls', 'Boarding', 'Regular', '14333201', 'HBDB'),
(gen_random_uuid(), 'Moi High Mbiruri', 'Eastern', 'Embu', 'Embu East', 'C1', 'Boys', 'Boarding', 'Regular', '14300006', 'E3HX'),
(gen_random_uuid(), 'Siakago Boys High School', 'Eastern', 'Embu', 'Mbeere North', 'C1', 'Boys', 'Boarding', 'Regular', '14312101', '5Q9M'),
(gen_random_uuid(), 'Siakago Girls High School', 'Eastern', 'Embu', 'Mbeere North', 'C1', 'Girls', 'Boarding', 'Regular', '14300011', '5ELL'),
(gen_random_uuid(), 'Nyangwa Boys'' High School', 'Eastern', 'Embu', 'Mbeere South', 'C1', 'Boys', 'Boarding', 'Regular', '14341201', 'FKUD'),
(gen_random_uuid(), 'Garissa High', 'North Eastern', 'Garissa', 'Garissa', 'C1', 'Boys', 'Boarding', 'Regular', '45800001', '5G35'),
(gen_random_uuid(), 'Nep Girls High', 'North Eastern', 'Garissa', 'Garissa', 'C1', 'Girls', 'Boarding', 'Regular', '45800002', '274N'),
(gen_random_uuid(), 'Homa Bay High School', 'Nyanza', 'Homa Bay', 'Homa Bay', 'C1', 'Boys', 'Boarding', 'Regular', '41704001', 'HQXM'),
(gen_random_uuid(), 'Ogande Girls'' High School', 'Nyanza', 'Homa Bay', 'Homa Bay', 'C1', 'Girls', 'Boarding', 'Regular', '41704003', 'HQ39'),
(gen_random_uuid(), 'Bishop Linus Okok Girls'' Secondary School', 'Nyanza', 'Homa Bay', 'Rachuonyo East', 'C1', 'Girls', 'Boarding', 'Regular', '41743103', 'FYVT'),
(gen_random_uuid(), 'Agoro Sare High School', 'Nyanza', 'Homa Bay', 'Rachuonyo Sout', 'C1', 'Boys', 'Boarding', 'Regular', '41710301', 'QERE'),
(gen_random_uuid(), 'Asumbi Girls', 'Nyanza', 'Homa Bay', 'Rangwe', 'C1', 'Girls', 'Boarding', 'Regular', '41700004', 'WMWC'),
(gen_random_uuid(), 'Orero Boys Secondary School', 'Nyanza', 'Homa Bay', 'Rangwe', 'C1', 'Boys', 'Boarding', 'Regular', '41742105', '5WQU'),
(gen_random_uuid(), 'Garbatula High School', 'Eastern', 'Isiolo', 'Garbatulla', 'C1', 'Boys', 'Boarding', 'Regular', '17300015', 'ZXZL'),
(gen_random_uuid(), 'Moi Girls Isinya', 'Rift Valley', 'Kajiado', 'Isinya', 'C1', 'Girls', 'Boarding', 'Regular', '31500011', 'VKMC'),
(gen_random_uuid(), 'Noonkopir Girls Secondary School', 'Rift Valley', 'Kajiado', 'Isinya', 'C1', 'Girls', 'Boarding', 'Regular', '31567201', 'B7C7'),
(gen_random_uuid(), 'Olkejuado High School', 'Rift Valley', 'Kajiado', 'Kajiado Central', 'C1', 'Boys', 'Boarding', 'Regular', '31515101', '5NZD'),
(gen_random_uuid(), 'Oloolaiser High School', 'Rift Valley', 'Kajiado', 'Kajiado North', 'C1', 'Boys', 'Boarding', 'Regular', '31500026', '3YA9'),
(gen_random_uuid(), 'Butere Girls High School', 'Western', 'Kakamega', 'Butere', 'C1', 'Girls', 'Boarding', 'Regular', '37600005', 'XT9Q'),
(gen_random_uuid(), 'Kakamega School', 'Western', 'Kakamega', 'Kakamega Centra', 'C1', 'Boys', 'Boarding', 'Regular', '37600001', '3NLD'),
(gen_random_uuid(), 'The Sacred Heart Girls, Mukumu', 'Western', 'Kakamega', 'Kakamega East', 'C1', 'Girls', 'Boarding', 'Regular', '37616007', 'SNFG'),
(gen_random_uuid(), 'Musingu Boys High School', 'Western', 'Kakamega', 'Kakamega South', 'C1', 'Boys', 'Boarding', 'Regular', '37615001', 'JCSP'),
(gen_random_uuid(), 'St. Peter''s Mumias Boys'' High School', 'Western', 'Kakamega', 'Mumias West', 'C1', 'Boys', 'Boarding', 'Regular', '37617211', 'F5U8'),
(gen_random_uuid(), 'Kabianga High School', 'Rift Valley', 'Kericho', 'Belgut', 'C1', 'Boys', 'Boarding', 'Regular', '28500006', 'HKSE'),
(gen_random_uuid(), 'A.I.C Litein Girls Secondary S Chool', 'Rift Valley', 'Kericho', 'Bureti', 'C1', 'Girls', 'Boarding', 'Regular', '28522520', 'UTE8'),
(gen_random_uuid(), 'Litein High School', 'Rift Valley', 'Kericho', 'Bureti', 'C1', 'Boys', 'Boarding', 'Regular', '28522505', 'CAYW'),
(gen_random_uuid(), 'Tengecha Boys High School', 'Rift Valley', 'Kericho', 'Bureti', 'C1', 'Boys', 'Boarding', 'Regular', '28522501', 'WRCH'),
(gen_random_uuid(), 'Tengecha Girls Secondary School', 'Rift Valley', 'Kericho', 'Bureti', 'C1', 'Girls', 'Boarding', 'Regular', '28522509', 'NAKY'),
(gen_random_uuid(), 'Moi Tea Girls Secondary School', 'Rift Valley', 'Kericho', 'Kericho', 'C1', 'Girls', 'Boarding', 'Regular', '28512112', 'FLFQ'),
(gen_random_uuid(), 'St.Francis Girls High School (Mang''u)', 'Central', 'Kiambu', 'Gatundu North', 'C1', 'Girls', 'Boarding', 'Regular', '11236101', 'QGQU'),
(gen_random_uuid(), 'Kambui Girls'' High School', 'Central', 'Kiambu', 'Githunguri', 'C1', 'Girls', 'Boarding', 'Regular', '11232101', 'SA3X'),
(gen_random_uuid(), 'Mangu High School', 'Central', 'Kiambu', 'Juja', 'C1', 'Boys', 'Boarding', 'Regular', '11200003', 'DJ8J'),
(gen_random_uuid(), 'Kiambu High School', 'Central', 'Kiambu', 'Kiambu', 'C1', 'Boys', 'Boarding', 'Regular', '11205204', '6ST4'),
(gen_random_uuid(), 'St. Anne''s Secondary School-Lioki', 'Central', 'Kiambu', 'Kiambu', 'C1', 'Girls', 'Boarding', 'Regular', '11205201', 'PSRL'),
(gen_random_uuid(), 'Alliance Girls'' High School', 'Central', 'Kiambu', 'Kikuyu', 'C1', 'Girls', 'Boarding', 'Regular', '11200002', 'C8FX'),
(gen_random_uuid(), 'Alliance High School', 'Central', 'Kiambu', 'Kikuyu', 'C1', 'Boys', 'Boarding', 'Regular', '11200001', 'RVPP'),
(gen_random_uuid(), 'Precious Blood Kagwe Girls Secondary School', 'Central', 'Kiambu', 'Lari', 'C1', 'Girls', 'Boarding', 'Regular', '11231102', 'CXQX'),
(gen_random_uuid(), 'Limuru Girls'' School', 'Central', 'Kiambu', 'Limuru', 'C1', 'Girls', 'Boarding', 'Regular', '11200004', 'VJHU'),
(gen_random_uuid(), 'Loreto High School Limuru', 'Central', 'Kiambu', 'Limuru', 'C1', 'Girls', 'Boarding', 'Regular', '11200005', 'GATC'),
(gen_random_uuid(), 'Our Lady Of Mt.Carmel Maryhill Girls', 'Central', 'Kiambu', 'Thika West', 'C1', 'Girls', 'Boarding', 'Regular', '11200006', 'FMPQ'),
(gen_random_uuid(), 'Thika High Sch', 'Central', 'Kiambu', 'Thika West', 'C1', 'Boys', 'Boarding', 'Regular', '11207101', 'HNYB'),
(gen_random_uuid(), 'Malindi High', 'Coast', 'Kilifi', 'Malindi', 'C1', 'Boys', 'Boarding', 'Regular', '4107101', '3Y3N'),
(gen_random_uuid(), 'Dr.Krapf', 'Coast', 'Kilifi', 'Rabai', 'C1', 'Boys', 'Boarding', 'Regular', '4122102', 'CALY'),
(gen_random_uuid(), 'Kombeni', 'Coast', 'Kilifi', 'Rabai', 'C1', 'Girls', 'Boarding', 'Regular', '4122103', 'XKHE'),
(gen_random_uuid(), 'Ribe Boys', 'Coast', 'Kilifi', 'Rabai', 'C1', 'Boys', 'Boarding', 'Regular', '4100002', '2LZD'),
(gen_random_uuid(), 'Ribe Girls', 'Coast', 'Kilifi', 'Rabai', 'C1', 'Girls', 'Boarding', 'Regular', '4122105', 'B4TS'),
(gen_random_uuid(), 'Mutira Girls Secondary School', 'Central', 'Kirinyaga', 'Kirinyaga Centra', 'C1', 'Girls', 'Boarding', 'Regular', '9203405', 'DH4N'),
(gen_random_uuid(), 'Kabare Girls'' High School', 'Central', 'Kirinyaga', 'Kirinyaga East', 'C1', 'Girls', 'Boarding', 'Regular', '9200011', 'SCEA'),
(gen_random_uuid(), 'Kianyaga High School', 'Central', 'Kirinyaga', 'Kirinyaga East', 'C1', 'Boys', 'Boarding', 'Regular', '9222201', 'PTQ6'),
(gen_random_uuid(), 'Baricho High School', 'Central', 'Kirinyaga', 'Kirinyaga West', 'C1', 'Boys', 'Boarding', 'Regular', '9200012', 'RVM4'),
(gen_random_uuid(), 'Riokindo High School', 'Nyanza', 'Kisii', 'Kenyenya', 'C1', 'Boys', 'Boarding', 'Regular', '40727101', 'EZ4P'),
(gen_random_uuid(), 'Kereri Girls High School', 'Nyanza', 'Kisii', 'Kisii Central', 'C1', 'Girls', 'Boarding', 'Regular', '40703103', '3UMS'),
(gen_random_uuid(), 'Kisii High', 'Nyanza', 'Kisii', 'Kisii Central', 'C1', 'Boys', 'Boarding', 'Regular', '40700002', 'WBX4'),
(gen_random_uuid(), 'Nyabururu Girls', 'Nyanza', 'Kisii', 'Kitutu Central', 'C1', 'Girls', 'Boarding', 'Regular', '40700003', 'C45H'),
(gen_random_uuid(), 'Kisumu Boys High School', 'Nyanza', 'Kisumu', 'Kisumu Central', 'C1', 'Boys', 'Boarding', 'Regular', '39741005', 'TEL2'),
(gen_random_uuid(), 'Kisumu Girls High School', 'Nyanza', 'Kisumu', 'Kisumu Central', 'C1', 'Girls', 'Boarding', 'Regular', '39700009', 'ATC6'),
(gen_random_uuid(), 'Maseno School', 'Nyanza', 'Kisumu', 'Kisumu West', 'C1', 'Boys', 'Boarding', 'Regular', '39700001', '8SWL'),
(gen_random_uuid(), 'Sinyolo Girls Secondary School', 'Nyanza', 'Kisumu', 'Kisumu West', 'C1', 'Girls', 'Boarding', 'Regular', '39737025', 'FB35'),
(gen_random_uuid(), 'Nyakach Girls'' High School', 'Nyanza', 'Kisumu', 'Nyakach', 'C1', 'Girls', 'Boarding', 'Regular', '39733213', '82QP'),
(gen_random_uuid(), 'Kitui High', 'Eastern', 'Kitui', 'Kitui Central', 'C1', 'Boys', 'Boarding', 'Regular', '13300007', 'A66N'),
(gen_random_uuid(), 'St Charles Lwanga School', 'Eastern', 'Kitui', 'Kitui Central', 'C1', 'Boys', 'Boarding', 'Regular', '13302102', '95WM'),
(gen_random_uuid(), 'Muthale Girls', 'Eastern', 'Kitui', 'Kitui West', 'C1', 'Girls', 'Boarding', 'Regular', '13300005', 'WC8Y'),
(gen_random_uuid(), 'Kimangao Girls Secondary School', 'Eastern', 'Kitui', 'Kyuso', 'C1', 'Girls', 'Boarding', 'Regular', '13328102', '6YHE'),
(gen_random_uuid(), 'Kinango Secondary School', 'Coast', 'Kwale', 'Kinango', 'C1', 'Boys', 'Boarding', 'Regular', '2109101', 'VLQH'),
(gen_random_uuid(), 'Kwale High', 'Coast', 'Kwale', 'Matuga', 'C1', 'Boys', 'Boarding', 'Regular', '2100005', 'P6GZ'),
(gen_random_uuid(), 'Matuga Girls Hgh Sch', 'Coast', 'Kwale', 'Matuga', 'C1', 'Girls', 'Boarding', 'Regular', '2100006', '6J6F'),
(gen_random_uuid(), 'Waa High', 'Coast', 'Kwale', 'Matuga', 'C1', 'Boys', 'Boarding', 'Regular', '2105104', 'LA49'),
(gen_random_uuid(), 'Nanyuki High School', 'Rift Valley', 'Laikipia', 'Laikipia East', 'C1', 'Boys', 'Boarding', 'Regular', '30500021', 'U8CD'),
(gen_random_uuid(), 'G.G Rumuruti Secondary School', 'Rift Valley', 'Laikipia', 'Laikipia West', 'C1', 'Boys', 'Boarding', 'Regular', '30544101', 'TQ24'),
(gen_random_uuid(), 'Gatero Girls High School', 'Rift Valley', 'Laikipia', 'Nyahururu', 'C1', 'Girls', 'Boarding', 'Regular', '30556101', 'RDGW'),
(gen_random_uuid(), 'Ndururumo High School', 'Rift Valley', 'Laikipia', 'Nyahururu', 'C1', 'Mixed', 'Boarding', 'Regular', '30556301', 'SA7G'),
(gen_random_uuid(), 'Njonjo Girls High School', 'Rift Valley', 'Laikipia', 'Nyahururu', 'C1', 'Girls', 'Boarding', 'Regular', '30500020', 'D2E4'),
(gen_random_uuid(), 'Lamu Girls', 'Coast', 'Lamu', 'Lamu Central', 'C1', 'Girls', 'Boarding', 'Regular', '06100011', '8WZT'),
(gen_random_uuid(), 'Kathiani Girls School', 'Eastern', 'Machakos', 'Kathiani', 'C1', 'Girls', 'Boarding', 'Regular', '12300013', 'N5AN'),
(gen_random_uuid(), 'Machakos Boys', 'Eastern', 'Machakos', 'Machakos', 'C1', 'Boys', 'Boarding', 'Regular', '12300001', 'S6CH'),
(gen_random_uuid(), 'Machakos Girls'' High School', 'Eastern', 'Machakos', 'Machakos', 'C1', 'Girls', 'Boarding', 'Regular', '12301702', 'YRLY'),
(gen_random_uuid(), 'Tala High School', 'Eastern', 'Machakos', 'Matungulu', 'C1', 'Boys', 'Boarding', 'Regular', '12345501', 'NWXY'),
(gen_random_uuid(), 'St. Joseph''s Girls Secondary Kibwezi', 'Eastern', 'Makueni', 'Kibwezi', 'C1', 'Girls', 'Boarding', 'Regular', '18325209', 'CXPV'),
(gen_random_uuid(), 'Precious Blood Secondary School - Kilungu', 'Eastern', 'Makueni', 'Kilungu', 'C1', 'Girls', 'Boarding', 'Regular', '18336101', 'G9D5'),
(gen_random_uuid(), 'Makueni Boys', 'Eastern', 'Makueni', 'Makueni', 'C1', 'Boys', 'Boarding', 'Regular', '18300003', 'A8KQ'),
(gen_random_uuid(), 'Makueni Girls High School', 'Eastern', 'Makueni', 'Makueni', 'C1', 'Girls', 'Boarding', 'Regular', '18307102', 'LH7J'),
(gen_random_uuid(), 'S.T Alphonsa Kisau Girls'' Secondary School', 'Eastern', 'Makueni', 'Mbooni East', 'C1', 'Girls', 'Boarding', 'Regular', '18346102', 'N7W7'),
(gen_random_uuid(), 'Mbooni Boys', 'Eastern', 'Makueni', 'Mbooni West', 'C1', 'Boys', 'Boarding', 'Regular', '18323102', '5VB6'),
(gen_random_uuid(), 'St Therese Mbooni Girls', 'Eastern', 'Makueni', 'Mbooni West', 'C1', 'Girls', 'Boarding', 'Regular', '18300016', '2C7G'),
(gen_random_uuid(), 'Mukaa Boys'' High School', 'Eastern', 'Makueni', 'Mukaa', 'C1', 'Boys', 'Boarding', 'Regular', '18347501', 'JC4P'),
(gen_random_uuid(), 'Matiliku Secondary School', 'Eastern', 'Makueni', 'Nzaui', 'C1', 'Boys', 'Boarding', 'Regular', '18324301', 'ZDJQ'),
(gen_random_uuid(), 'Mandera Secondary School', 'North Eastern', 'Mandera', 'Mandera East', 'C1', 'Boys', 'Boarding', 'Regular', '47800005', '976X'),
(gen_random_uuid(), 'Moi Girls Secondary', 'North Eastern', 'Mandera', 'Mandera East', 'C1', 'Girls', 'Boarding', 'Regular', '47800006', '3GD6'),
(gen_random_uuid(), 'Moi Girls Secondary School- Marsabit', 'Eastern', 'Marsabit', 'Marsabit', 'C1', 'Girls', 'Boarding', 'Regular', '16300008', 'DAH8'),
(gen_random_uuid(), 'Moyale Secondary School', 'Eastern', 'Marsabit', 'Moyale', 'C1', 'Boys', 'Boarding', 'Regular', '16300014', 'B956'),
(gen_random_uuid(), 'St. Mary''s Girls High School Igoji', 'Eastern', 'Meru', 'Igoji', 'C1', 'Girls', 'Boarding', 'Regular', '15300012', 'MY4N'),
(gen_random_uuid(), 'Kaaga Girls'' High School', 'Eastern', 'Meru', 'Imenti East', 'C1', 'Girls', 'Boarding', 'Regular', '15374102', 'JYVC'),
(gen_random_uuid(), 'Meru School', 'Eastern', 'Meru', 'Imenti East', 'C1', 'Boys', 'Boarding', 'Regular', '15300002', 'J5DS'),
(gen_random_uuid(), 'Nkubu High School', 'Eastern', 'Meru', 'Imenti South', 'C1', 'Boys', 'Boarding', 'Regular', '15319101', 'GEML'),
(gen_random_uuid(), 'St. Albert''s Girls High School, Ulanda', 'Nyanza', 'Migori', 'Awendo', 'C1', 'Girls', 'Boarding', 'Regular', '44739104', 'EW7R'),
(gen_random_uuid(), 'Tarang''anya Boys High School', 'Nyanza', 'Migori', 'Kuria West', 'C1', 'Boys', 'Boarding', 'Regular', '44708101', 'DSMS'),
(gen_random_uuid(), 'Moi Nyabohanse Girls High School', 'Nyanza', 'Migori', 'Mabera', 'C1', 'Girls', 'Boarding', 'Regular', '44700011', 'D9ZS'),
(gen_random_uuid(), 'Kadika Girls'' Secondary School', 'Nyanza', 'Migori', 'Migori', 'C1', 'Girls', 'Boarding', 'Regular', '44707105', 'U7D5'),
(gen_random_uuid(), 'Kanga High', 'Nyanza', 'Migori', 'Rongo', 'C1', 'Boys', 'Boarding', 'Regular', '44700006', '9KQC'),
(gen_random_uuid(), 'St Joseph''s Rapogi Secondary School', 'Nyanza', 'Migori', 'Uriri', 'C1', 'Boys', 'Boarding', 'Regular', '44736101', 'UQDE'),
(gen_random_uuid(), 'Mama Ngina Girls', 'Coast', 'Mombasa', 'Kisauni', 'C1', 'Girls', 'Boarding', 'Regular', '3100001', 'W3WT'),
(gen_random_uuid(), 'Shimo-La-Tewa School', 'Coast', 'Mombasa', 'Kisauni', 'C1', 'Boys', 'Boarding', 'Regular', '3100007', 'P8NT'),
(gen_random_uuid(), 'Kahuhia Girls'' High School', 'Central', 'Murang''a', 'Kahuro', 'C1', 'Girls', 'Boarding', 'Regular', '10238101', 'Q835'),
(gen_random_uuid(), 'Kiaguthu Boys Secondary School', 'Central', 'Murang''a', 'Kahuro', 'C1', 'Boys', 'Boarding', 'Regular', '10238114', 'BTL6'),
(gen_random_uuid(), 'Mugoiri Girls High School', 'Central', 'Murang''a', 'Kahuro', 'C1', 'Girls', 'Boarding', 'Regular', '10200013', '42MW'),
(gen_random_uuid(), 'Njiiri School', 'Central', 'Murang''a', 'Kigumo', 'C1', 'Boys', 'Boarding', 'Regular', '10227301', 'D2QA'),
(gen_random_uuid(), 'Muranga High - Public', 'Central', 'Murang''a', 'Murang''a East', 'C1', 'Boys', 'Boarding', 'Regular', '10200008', 'D2VN'),
(gen_random_uuid(), 'Kamahuha Girls High School', 'Central', 'Murang''a', 'Murang''a South', 'C1', 'Girls', 'Boarding', 'Regular', '10208201', 'XAUE'),
(gen_random_uuid(), 'Precious Blood Riruta', 'Nairobi', 'Nairobi', 'Dagoretti', 'C1', 'Girls', 'Boarding', 'Regular', '20405004', 'P5US'),
(gen_random_uuid(), 'Moi Forces', 'Nairobi', 'Nairobi', 'Kamukunji', 'C1', 'Boys', 'Boarding', 'Regular', '20400008', '3UKL'),
(gen_random_uuid(), 'Starehe Girls', 'Nairobi', 'Nairobi', 'Kasarani', 'C1', 'Girls', 'Boarding', 'Regular', '20400009', 'KJTC'),
(gen_random_uuid(), 'Buruburu Girls Secondary', 'Nairobi', 'Nairobi', 'Makadara', 'C1', 'Girls', 'Boarding', 'Regular', '20401007', 'PF86'),
(gen_random_uuid(), 'Pangani Girls', 'Nairobi', 'Nairobi', 'Starehe', 'C1', 'Girls', 'Boarding', 'Regular', '20400006', 'DZNA'),
(gen_random_uuid(), 'Starehe Boys', 'Nairobi', 'Nairobi', 'Starehe', 'C1', 'Boys', 'Boarding', 'Regular', '20400004', 'YS3B'),
(gen_random_uuid(), 'Kenya High Sch', 'Nairobi', 'Nairobi', 'Westlands', 'C1', 'Girls', 'Boarding', 'Regular', '20400003', 'UX27'),
(gen_random_uuid(), 'Nairobi Sch', 'Nairobi', 'Nairobi', 'Westlands', 'C1', 'Boys', 'Boarding', 'Regular', '20400002', 'GHXC'),
(gen_random_uuid(), 'St Georges Girls', 'Nairobi', 'Nairobi', 'Westlands', 'C1', 'Girls', 'Boarding', 'Regular', '20406011', '8XQJ'),
(gen_random_uuid(), 'State House Girls', 'Nairobi', 'Nairobi', 'Westlands', 'C1', 'Girls', 'Boarding', 'Regular', '20406002', 'HFQ3'),
(gen_random_uuid(), 'Utumishi Boys Academy', 'Rift Valley', 'Nakuru', 'Gilgil', 'C1', 'Boys', 'Boarding', 'Regular', '27500008', 'D3WB'),
(gen_random_uuid(), 'Utumishi Girls Academy', 'Rift Valley', 'Nakuru', 'Gilgil', 'C1', 'Girls', 'Boarding', 'Regular', '27500010', 'RE74'),
(gen_random_uuid(), 'Mary Mount Secondary School', 'Rift Valley', 'Nakuru', 'Molo', 'C1', 'Girls', 'Boarding', 'Regular', '27538204', 'X77F'),
(gen_random_uuid(), 'Molo Academy Boys Secondary School', 'Rift Valley', 'Nakuru', 'Molo', 'C1', 'Boys', 'Boarding', 'Regular', '27538208', 'QNDP'),
(gen_random_uuid(), 'Naivasha Girls Secondary School', 'Rift Valley', 'Nakuru', 'Naivasha', 'C1', 'Girls', 'Boarding', 'Regular', '27537301', '8KPJ'),
(gen_random_uuid(), 'Nakuru Girls'' High School', 'Rift Valley', 'Nakuru', 'Nakuru East', 'C1', 'Girls', 'Boarding', 'Regular', '27500009', 'CJQE'),
(gen_random_uuid(), 'Moi Forces Academy Lanet', 'Rift Valley', 'Nakuru', 'Nakuru North', 'C1', 'Girls', 'Boarding', 'Regular', '27500007', 'K44P'),
(gen_random_uuid(), 'St. Bakhita Bahati Girls Secondary School', 'Rift Valley', 'Nakuru', 'Nakuru North', 'C1', 'Girls', 'Boarding', 'Regular', '27536202', 'NGR9'),
(gen_random_uuid(), 'Njoro Boys High School', 'Rift Valley', 'Nakuru', 'Njoro', 'C1', 'Boys', 'Boarding', 'Regular', '27564101', 'UL3F'),
(gen_random_uuid(), 'Kapsabet Boys', 'Rift Valley', 'Nandi', 'Chesumei', 'C1', 'Boys', 'Boarding', 'Regular', '29500006', 'JBLC'),
(gen_random_uuid(), 'St. Joseph''s Girls - Chepterit', 'Rift Valley', 'Nandi', 'Chesumei', 'C1', 'Girls', 'Boarding', 'Regular', '29500025', 'CF3V'),
(gen_random_uuid(), 'Kapsabet Girls', 'Rift Valley', 'Nandi', 'Nandi Central', 'C1', 'Girls', 'Boarding', 'Regular', '29513101', 'YMEL'),
(gen_random_uuid(), 'Meteitei Boys Secondary School', 'Rift Valley', 'Nandi', 'Tinderet', 'C1', 'Boys', 'Boarding', 'Regular', '29542101', 'DC6B'),
(gen_random_uuid(), 'Narok High School', 'Rift Valley', 'Narok', 'Narok Central', 'C1', 'Boys', 'Boarding', 'Regular', '32589101', 'KKEW'),
(gen_random_uuid(), 'Kilgoris Boys Secondary School', 'Rift Valley', 'Narok', 'Trans Mara West', 'C1', 'Boys', 'Boarding', 'Regular', '32500016', 'KUAC'),
(gen_random_uuid(), 'Nyambaria High School', 'Nyanza', 'Nyamira', 'Manga', 'C1', 'Boys', 'Boarding', 'Regular', '43700008', 'VQT5'),
(gen_random_uuid(), 'Kebirigo High School', 'Nyanza', 'Nyamira', 'Nyamira', 'C1', 'Boys', 'Boarding', 'Regular', '43706115', 'UUZ3'),
(gen_random_uuid(), 'Sironga Girls High School', 'Nyanza', 'Nyamira', 'Nyamira', 'C1', 'Girls', 'Boarding', 'Regular', '43700012', '2GPC'),
(gen_random_uuid(), 'Karima Girls', 'Central', 'Nyandarua', 'North Kinangop', 'C1', 'Girls', 'Boarding', 'Regular', '07200009', 'XQVS'),
(gen_random_uuid(), 'Magomano Secondary School', 'Central', 'Nyandarua', 'North Kinangop', 'C1', 'Girls', 'Boarding', 'Regular', '07209102', 'LNF2'),
(gen_random_uuid(), 'Nyandarua High School', 'Central', 'Nyandarua', 'Nyandarua Centr', 'C1', 'Mixed', 'Boarding', 'Regular', '07200014', 'EEAR'),
(gen_random_uuid(), 'Nyahururu High School', 'Central', 'Nyandarua', 'Nyandarua West', 'C1', 'Boys', 'Boarding', 'Regular', '07214101', 'H7H8'),
(gen_random_uuid(), 'Njabini Boys High School', 'Central', 'Nyandarua', 'South Kinangop', 'C1', 'Boys', 'Boarding', 'Regular', '07216101', 'TBFM'),
(gen_random_uuid(), 'Bishop Gatimu Ngandu Girls', 'Central', 'Nyeri', 'Mathira West', 'C1', 'Girls', 'Boarding', 'Regular', '08200010', 'G26G'),
(gen_random_uuid(), 'South Tetu Girls', 'Central', 'Nyeri', 'Mukurwe-ini', 'C1', 'Girls', 'Boarding', 'Regular', '08219101', '9CZX'),
(gen_random_uuid(), 'Kagumo High', 'Central', 'Nyeri', 'Nyeri Central', 'C1', 'Boys', 'Boarding', 'Regular', '08200007', '442P'),
(gen_random_uuid(), 'Nyeri High School', 'Central', 'Nyeri', 'Nyeri Central', 'C1', 'Boys', 'Boarding', 'Regular', '08202001', 'V6YZ'),
(gen_random_uuid(), 'Mahiga Girls', 'Central', 'Nyeri', 'Nyeri South', 'C1', 'Girls', 'Boarding', 'Regular', '08237012', '4FPL'),
(gen_random_uuid(), 'Othaya Boys High School', 'Central', 'Nyeri', 'Nyeri South', 'C1', 'Boys', 'Boarding', 'Regular', '08237005', 'XCY9'),
(gen_random_uuid(), 'Kisima Girls High School', 'Rift Valley', 'Samburu', 'Samburu Centra', 'C1', 'Girls', 'Boarding', 'Regular', '22500024', '3LC3'),
(gen_random_uuid(), 'Maralal High School', 'Rift Valley', 'Samburu', 'Samburu Centra', 'C1', 'Boys', 'Boarding', 'Regular', '22500013', '5VVT'),
(gen_random_uuid(), 'Maranda High', 'Nyanza', 'Siaya', 'Bondo', 'C1', 'Boys', 'Boarding', 'Regular', '42700005', '7XSS'),
(gen_random_uuid(), 'Sawagongo High School', 'Nyanza', 'Siaya', 'Gem Yala', 'C1', 'Boys', 'Boarding', 'Regular', '42749107', 'WY37'),
(gen_random_uuid(), 'St. Mary''s School, Yala', 'Nyanza', 'Siaya', 'Gem Yala', 'C1', 'Boys', 'Boarding', 'Regular', '42749101', '7SG8'),
(gen_random_uuid(), 'Ramba Secondary School', 'Nyanza', 'Siaya', 'Rarieda', 'C1', 'Boys', 'Boarding', 'Regular', '42721202', 'GB9M'),
(gen_random_uuid(), 'St Mary''s Lwak Girls'' School', 'Nyanza', 'Siaya', 'Rarieda', 'C1', 'Girls', 'Boarding', 'Regular', '42721201', 'XBRN'),
(gen_random_uuid(), 'Ngiya Girls High School', 'Nyanza', 'Siaya', 'Siaya', 'C1', 'Girls', 'Boarding', 'Regular', '42700007', 'XLHN'),
(gen_random_uuid(), 'St. Francis Rang''ala Girls Secondary School', 'Nyanza', 'Siaya', 'Ugunja', 'C1', 'Girls', 'Boarding', 'Regular', '42738101', '9WL7'),
(gen_random_uuid(), 'Bura Girls', 'Coast', 'Taita Taveta', 'Mwatate', 'C1', 'Girls', 'Boarding', 'Regular', '1100004', 'SPRV'),
(gen_random_uuid(), 'Kenyatta High Mwatate', 'Coast', 'Taita Taveta', 'Mwatate', 'C1', 'Boys', 'Boarding', 'Regular', '1100003', 'L6WF'),
(gen_random_uuid(), 'Dr.Aggrey High School', 'Coast', 'Taita Taveta', 'Taita', 'C1', 'Boys', 'Boarding', 'Regular', '1101101', 'FV6C'),
(gen_random_uuid(), 'Ngao Girls Secondary School', 'Coast', 'Tana River', 'Tana Delta', 'C1', 'Girls', 'Boarding', 'Regular', '5100010', 'YJHM'),
(gen_random_uuid(), 'Hola Boys Secondary School', 'Coast', 'Tana River', 'Tana River', 'C1', 'Boys', 'Boarding', 'Regular', '5100009', '6EFL'),
(gen_random_uuid(), 'Chogoria Boys High School', 'Eastern', 'Tharaka Nithi', 'Maara', 'C1', 'Boys', 'Boarding', 'Regular', '19326201', 'M5PG'),
(gen_random_uuid(), 'Chogoria Girls', 'Eastern', 'Tharaka Nithi', 'Maara', 'C1', 'Girls', 'Boarding', 'Regular', '19300004', '3FF4'),
(gen_random_uuid(), 'Kiriani Boys High School', 'Eastern', 'Tharaka Nithi', 'Maara', 'C1', 'Boys', 'Boarding', 'Regular', '19326203', '9S4F'),
(gen_random_uuid(), 'Ikuu Boys High School', 'Eastern', 'Tharaka Nithi', 'Meru South', 'C1', 'Boys', 'Boarding', 'Regular', '19300010', 'YTB4'),
(gen_random_uuid(), 'St Brigids Kiminini', 'Rift Valley', 'Trans Nzoia', 'Kiminini', 'C1', 'Girls', 'Boarding', 'Regular', '23500003', 'Q823'),
(gen_random_uuid(), 'St. Anthony''s Boys'' High School - Kitale', 'Rift Valley', 'Trans Nzoia', 'Kiminini', 'C1', 'Boys', 'Boarding', 'Regular', '23574101', '27EL'),
(gen_random_uuid(), 'St. Joseph''s Boys High School - Kitale', 'Rift Valley', 'Trans Nzoia', 'Trans Nzoia West', 'C1', 'Boys', 'Boarding', 'Regular', '23500014', '9FRM'),
(gen_random_uuid(), 'Katilu Girls'' Secondary School', 'Rift Valley', 'Turkana', 'Aroo', 'C1', 'Girls', 'Boarding', 'Regular', '21592302', '8BQ6'),
(gen_random_uuid(), 'Turkana Girls'' Secondary School', 'Rift Valley', 'Turkana', 'Loima', 'C1', 'Girls', 'Boarding', 'Regular', '21500021', 'C2JL'),
(gen_random_uuid(), 'Lodwar Boys High School', 'Rift Valley', 'Turkana', 'Turkana Central', 'C1', 'Boys', 'Boarding', 'Regular', '21500012', '9GYY'),
(gen_random_uuid(), 'Moi Girls'' High School- Eldoret', 'Rift Valley', 'Uasin Gishu', 'Ainabkoi', 'C1', 'Girls', 'Boarding', 'Regular', '26500001', 'LVR8'),
(gen_random_uuid(), 'A.I.C. Chebisaas Boys Secondary School', 'Rift Valley', 'Uasin Gishu', 'Moiben', 'C1', 'Boys', 'Boarding', 'Regular', '26500002', '6WF4'),
(gen_random_uuid(), 'Paul Boit Boys Secondary School', 'Rift Valley', 'Uasin Gishu', 'Turbo', 'C1', 'Boys', 'Boarding', 'Regular', '26509114', 'YFES'),
(gen_random_uuid(), 'Nyang''ori Boys High School', 'Western', 'Vihiga', 'Hamisi', 'C1', 'Boys', 'Boarding', 'Regular', '38619102', 'HYCG'),
(gen_random_uuid(), 'Bunyore Girls', 'Western', 'Vihiga', 'Luanda', 'C1', 'Girls', 'Boarding', 'Regular', '38600003', 'A3ZW'),
(gen_random_uuid(), 'Chavakali High School', 'Western', 'Vihiga', 'Sabatia', 'C1', 'Boys', 'Boarding', 'Regular', '38600006', 'VSCS'),
(gen_random_uuid(), 'Friends School Keveye Girls', 'Western', 'Vihiga', 'Sabatia', 'C1', 'Girls', 'Boarding', 'Regular', '38622203', 'Y5NJ'),
(gen_random_uuid(), 'Wajir Girls Secondary School', 'North Eastern', 'Wajir', 'Wajir East', 'C1', 'Girls', 'Boarding', 'Regular', '46800004', 'P253'),
(gen_random_uuid(), 'Wajir High School', 'North Eastern', 'Wajir', 'Wajir East', 'C1', 'Boys', 'Boarding', 'Regular', '46800003', 'MMLZ'),
(gen_random_uuid(), 'Chewoyet High School', 'Rift Valley', 'West Pokot', 'West Pokot', 'C1', 'Boys', 'Boarding', 'Regular', '24500022', 'XJVN'),
(gen_random_uuid(), 'Kapenguria School', 'Rift Valley', 'West Pokot', 'West Pokot', 'C1', 'Boys', 'Boarding', 'Regular', '24505104', '7KRE'),
(gen_random_uuid(), 'Nasokol Girls Secondary School', 'Rift Valley', 'West Pokot', 'West Pokot', 'C1', 'Girls', 'Boarding', 'Regular', '24505102', 'TAGT'),
(gen_random_uuid(), 'St.Theresa''s Tartar Girls Secondary School', 'Rift Valley', 'West Pokot', 'West Pokot', 'C1', 'Girls', 'Boarding', 'Regular', '24500004', 'M4YT')
ON CONFLICT DO NOTHING;

-- career_pathways: 8 broad KJSA-aligned pathways. required_cluster_min is a
-- floor, not a ceiling: C1 (this seed's only tier) outranks C2-C4, so every
-- pathway currently recommends from the same C1 pool until C2-C4 are
-- ingested in a later phase. recommended_regions/counties are informational
-- badges only, not a hard filter (see api/schools/pathway-recommendations).
INSERT INTO career_pathways (id, name, slug, description, icon, required_cluster_min, recommended_regions, recommended_counties, career_tags)
VALUES
(gen_random_uuid(), 'STEM', 'stem', 'Sciences, Technology, Engineering & Mathematics — for students who enjoy problem-solving, experiments and building things.', '🔬', 'C2', ARRAY['Nairobi','Central','Rift Valley'], ARRAY['Nairobi','Kiambu','Nakuru'], ARRAY['Engineering','Medicine','Computer Science','Data Science']),
(gen_random_uuid(), 'Humanities & Social Sciences', 'humanities-social-sciences', 'Law, governance, culture and society — for students who enjoy reading, debate and understanding people.', '📚', 'C3', ARRAY['Nairobi','Nyanza','Western'], ARRAY['Nairobi','Kisumu','Kakamega'], ARRAY['Law','Teaching','Journalism','Psychology']),
(gen_random_uuid(), 'Business Studies', 'business-studies', 'Commerce, finance and entrepreneurship — for students who enjoy numbers, markets and running things.', '💼', 'C3', ARRAY['Nairobi','Central','Coast'], ARRAY['Nairobi','Kiambu','Mombasa'], ARRAY['Accounting','Finance','Marketing','Entrepreneurship']),
(gen_random_uuid(), 'Creative & Performing Arts', 'creative-performing-arts', 'Design, film, music and fashion — for students who express themselves through art and performance.', '🎨', 'C4', ARRAY['Nairobi','Coast'], ARRAY['Nairobi','Mombasa'], ARRAY['Design','Film','Music','Fashion']),
(gen_random_uuid(), 'Agriculture', 'agriculture', 'Farming, agribusiness and food systems — for students interested in land, livestock and food production.', '🌾', 'C4', ARRAY['Rift Valley','Central','Eastern'], ARRAY['Nakuru','Meru','Bungoma'], ARRAY['Agribusiness','Veterinary Science','Food Science']),
(gen_random_uuid(), 'Health Sciences', 'health-sciences', 'Nursing, medicine and public health — for students who want to care for people and communities.', '🏥', 'C2', ARRAY['Nairobi','Nyanza','Central'], ARRAY['Nairobi','Kisumu','Nyeri'], ARRAY['Nursing','Clinical Medicine','Pharmacy','Public Health']),
(gen_random_uuid(), 'Technical & Vocational', 'technical-vocational', 'Electrical, automotive, construction and ICT trades — for hands-on, practical problem-solvers.', '🔧', 'C4', ARRAY['Rift Valley','Western','Nairobi'], ARRAY['Uasin Gishu','Bungoma','Nairobi'], ARRAY['Electrical','Automotive','Construction','ICT Technician']),
(gen_random_uuid(), 'Hospitality & Tourism', 'hospitality-tourism', 'Hotels, travel and tourism — for students who enjoy people, service and Kenya''s tourism industry.', '🏨', 'C4', ARRAY['Coast','Rift Valley','Nairobi'], ARRAY['Mombasa','Narok','Nairobi'], ARRAY['Hotel Management','Tour Guiding','Culinary Arts'])
ON CONFLICT (slug) DO NOTHING;
