import { CheckCircle, Sparkles } from 'lucide-react'

interface ProgramVerificationBadgeProps {
  isVerified: boolean
  isAiGenerated: boolean
  size?: 'sm' | 'md'
}

const AI_GENERATED_TOOLTIP =
  'This program information was generated by AI and may not be fully accurate. Please verify with the university before applying.'

// No badge for legacy rows where both flags are false/null - only take a
// stance (verified or AI-generated/unverified) when we actually know one.
export default function ProgramVerificationBadge({
  isVerified,
  isAiGenerated,
  size = 'sm',
}: ProgramVerificationBadgeProps) {
  const sizeClasses = size === 'md' ? 'text-sm px-3 py-1 gap-1.5' : 'text-xs px-2 py-0.5 gap-1'
  const iconSize = size === 'md' ? 'w-4 h-4' : 'w-3 h-3'

  if (isVerified) {
    return (
      <span
        className={`inline-flex items-center ${sizeClasses} rounded-full font-medium bg-success/10 text-success`}
        title="Confirmed accurate by ElimuX"
      >
        <CheckCircle className={iconSize} />
        Verified
      </span>
    )
  }

  if (isAiGenerated) {
    return (
      <span
        className={`inline-flex items-center ${sizeClasses} rounded-full font-medium bg-warning/10 text-warning`}
        title={AI_GENERATED_TOOLTIP}
      >
        <Sparkles className={iconSize} />
        AI-generated · unverified
      </span>
    )
  }

  return null
}
